export const NOTES: {
  title: string;
  body: string;
  category: string;
  kind: "fact" | "rule" | "layout" | "example" | "pitfall";
}[] = [
  {
    title: "How do I sign a Binance API request with HMAC-SHA256?",
    body: "Build the exact query string (or URL-encoded body for POST) of all parameters you will send, in the same order. Compute HMAC-SHA256 of that string using your API secret, hex-encode it, and append it as the LAST parameter: `&signature=<hex>`. Send your API key in the `X-MBX-APIKEY` header. Signed (TRADE/USER_DATA) endpoints require a `timestamp` parameter in server milliseconds and accept an optional `recvWindow`. The signature itself is never part of the signed payload. Content type is `application/x-www-form-urlencoded`. The same scheme works on spot `/api/v3` and USD-M futures `/fapi/v1`. Most 'signature invalid' errors (-1022) come from re-serializing the body differently than what was signed, or from URL-encoding mismatches.",
    category: "Authentication and signing",
    kind: "example",
  },
  {
    title: "Why do I get Binance error -1021 (timestamp outside recvWindow)?",
    body: "-1021 means your `timestamp` differs from Binance server time by more than `recvWindow` (default 5000 ms, max 60000 ms). Root causes: local clock drift, NTP disabled, or a request that sat in a client-side rate-limit queue after its timestamp was generated. Fix: at startup fetch `GET /api/v3/time` (or `/fapi/v1/time`), compute `offset = serverTime - localTime`, apply it to every signed request, and refresh periodically. Generate the timestamp immediately before sending, not before queueing. Keep NTP running. Do not paper over drift by setting `recvWindow=60000` permanently — a wide window also widens the replay-attack surface. CCXT has `options.adjustForTimeDifference` for exactly this.",
    category: "Authentication and signing",
    kind: "pitfall",
  },
  {
    title: "Can I use Ed25519 or RSA keys instead of HMAC on Binance?",
    body: "Yes. As of early 2026 Binance supports asymmetric API keys — Ed25519 (recommended) and RSA (PKCS#8) — on spot and futures, including the WebSocket API. You generate the key pair locally, upload only the PUBLIC key in API Management, and sign the same payload string with your private key (Ed25519 signature, base64-encoded, appended as `signature=`). The `X-MBX-APIKEY` header then carries the key identifier Binance assigned. Advantages: the secret never leaves your machine, signing is fast, and key rotation does not expose a shared HMAC secret in config. Verify the exact signature encoding and supported endpoints in the current docs — asymmetric-key rollout has been expanding endpoint by endpoint.",
    category: "Authentication and signing",
    kind: "fact",
  },
  {
    title: "How do I sign a Bybit v5 API request?",
    body: "Bybit v5 signing: build the pre-sign string by concatenating `timestamp + apiKey + recvWindow + payload`, where payload is the raw query string for GET or the raw JSON body string for POST. HMAC-SHA256 it with your API secret and hex-encode. Send headers: `X-BAPI-API-KEY`, `X-BAPI-SIGN`, `X-BAPI-TIMESTAMP`, `X-BAPI-RECV-WINDOW` (default 5000 ms), and `X-BAPI-SIGN-TYPE: 2`. Get server time from `GET /v5/market/time`. Common failures: signing a re-serialized JSON body whose key order or whitespace differs from the body actually sent (sign the exact string you transmit), timestamp drift, and forgetting that the payload for GET must include the full query string in the order sent.",
    category: "Authentication and signing",
    kind: "example",
  },
  {
    title: "How does OKX signing work (passphrase and base64 HMAC)?",
    body: "OKX pre-hash string: `timestamp + method + requestPath + body`, where timestamp is ISO-8601 with milliseconds (e.g. `2026-01-01T00:00:00.000Z`), method is uppercase (`GET`/`POST`), requestPath includes the query string (`/api/v5/trade/order?instId=...`), and body is the raw JSON for POST (empty string otherwise). HMAC-SHA256 with your secret, then BASE64-encode (not hex — a classic porting bug). Headers: `OK-ACCESS-KEY`, `OK-ACCESS-SIGN`, `OK-ACCESS-TIMESTAMP`, and `OK-ACCESS-PASSPHRASE` — the passphrase you set when creating the key; a wrong passphrase is the most common OKX 401 cause. Timestamps must be within 30 s of server time (`GET /api/v5/public/time`). Demo trading additionally needs header `x-simulated-trading: 1`.",
    category: "Authentication and signing",
    kind: "example",
  },
  {
    title: "How do Binance weight-based rate limits work?",
    body: "Binance meters requests by 'weight', not count: each endpoint costs a documented weight (cheap lookups = 1, `exchangeInfo` is heavy, 10+). Limits are defined per interval in the `rateLimits` array of `GET /api/v3/exchangeInfo` — historically 1200 weight per minute per IP on spot (verify live values as of early 2026; Binance has been moving some limits to per-UID). Track usage from response headers like `X-MBX-USED-WEIGHT-1M` and throttle client-side around 80% of the cap. Placing an order costs weight AND, on futures, also counts against separate order-count limits (also listed in exchangeInfo). Cache exchangeInfo instead of re-fetching it per call — that alone saves most bots hundreds of weight per minute.",
    category: "Rate limits and bans",
    kind: "fact",
  },
  {
    title: "What is the difference between HTTP 429 and 418 on Binance?",
    body: "HTTP 429 means you violated a rate limit: back off immediately and respect the `Retry-After` header if present. If you keep hammering after 429s, Binance escalates to HTTP 418 — an IP ban whose duration grows with repeat offenses, from minutes up to multiple days. A ban blocks ALL API traffic from that IP, so one runaway loop can take down every strategy on the box. Rules: never retry a 429/418 instantly; use exponential backoff with jitter; route all requests through one throttled client so concurrent strategies share the budget; and treat a 418 as a circuit breaker that halts trading until the ban lifts. The same 429/418 semantics apply on futures and the WebSocket API.",
    category: "Rate limits and bans",
    kind: "rule",
  },
  {
    title: "How do I read Bybit v5 per-endpoint rate limit headers?",
    body: "Bybit v5 enforces per-endpoint, per-UID (and per-IP) limits, and trade endpoints report them in response headers: `X-Bapi-Limit` (bucket size), `X-Bapi-Limit-Status` (remaining), and `X-Bapi-Limit-Reset-Timestamp` (ms when the bucket refills). Order placement endpoints such as `/v5/order/create` have their own buckets, and the sizes vary by account/VIP tier — so do not hardcode numbers you found in a blog post; read the headers at runtime and adapt. When exceeded you get HTTP 403 with retCode 10006; wait until the reset timestamp, do not spin. If headers show you are chronically near the cap, use batch endpoints (`/v5/order/create-batch`) or apply for a limit raise rather than shaving margins ever thinner.",
    category: "Rate limits and bans",
    kind: "fact",
  },
  {
    title: "What are OKX rate limits and how do I stay under them?",
    body: "OKX expresses limits per endpoint as 'N requests per 2 seconds' — e.g. 20 req/2s is typical for public endpoints, with private endpoints having their own values in the docs. There is no weight header system like Binance, so throttle client-side per endpoint path. Exceeding a limit returns error code 50011 ('Request too frequent'); back off rather than retrying instantly, since persistent abuse can throttle the sub-account or IP further. Batch endpoints are your friend: `/api/v5/trade/batch-orders` places up to 20 orders in one request, and batch amend/cancel endpoints similarly amortize cost — grid and market-making bots should batch by default. Note that limits for the same endpoint can differ between live and demo (`x-simulated-trading`) environments.",
    category: "Rate limits and bans",
    kind: "fact",
  },
  {
    title: "Do WebSocket connections have rate limits too?",
    body: "Yes, on connection count, message rate, and stream count. Binance spot WS limits connection attempts (historically 300 per 5 minutes per IP) and caps streams per connection (1024), so combine streams into one `stream?streams=a/b/c` connection instead of opening one socket per symbol. Inbound messages (subscribe frames, WS API calls) are also rate-limited per connection. The Binance WebSocket API (`wss://ws-api.binance...`) lets you place orders over WS: each call is signed per-request (HMAC or Ed25519) and consumes the same weight budget as REST, but with lower overhead — useful for latency-sensitive order paths. Bybit v5 and OKX similarly limit subscribe messages and require periodic app-level pings. Verify exact numbers in current docs; they drift.",
    category: "Rate limits and bans",
    kind: "fact",
  },
  {
    title: "Market vs limit vs post-only — which order type should my bot use?",
    body: "Market guarantees a fill, not a price: on thin books you pay slippage, and on futures market orders still have a price-protection band that can leave you partially filled. Limit guarantees a price, not a fill. Post-only (Binance spot `LIMIT_MAKER`, Binance futures timeInForce `GTX`, Bybit v5 `PostOnly`) guarantees you are the maker: the exchange REJECTS the order instead of crossing the spread. Maker orders pay lower (or negative) fees, which is often the whole edge — but your bot must handle post-only rejections by requoting, or it silently stops trading. Taker exits for stop-loss logic are usually still worth the fee: a guaranteed exit beats a maker order that never fills while the market runs away.",
    category: "Orders and fills",
    kind: "rule",
  },
  {
    title: "What do GTC, IOC, FOK and GTX time-in-force values mean?",
    body: "GTC rests on the book until filled or canceled. IOC fills what it can immediately and cancels the remainder — partial fills are normal, so always read `executedQty` before assuming your exit happened. FOK is all-or-nothing: fill completely now or cancel entirely. GTX (Binance futures) is 'Good Till Crossing', i.e. post-only GTC; on Binance spot the equivalent is order type `LIMIT_MAKER` rather than a timeInForce. Bybit v5 uses `timeInForce: GTC/IOC/FOK/PostOnly`. OKX uses `ordType` variants (`post_only`, `ioc`, `fok`). Gotcha: default timeInForce differs between exchanges and even between order types on the same exchange — always set it explicitly, never rely on the default.",
    category: "Orders and fills",
    kind: "fact",
  },
  {
    title: "How do stop orders work and which trigger price should I use?",
    body: "A stop-market order fires a market order at the trigger: guaranteed execution, no guaranteed price — in a cascade it can fill far through your stop. A stop-limit fires a limit order: in a gap it may never fill, leaving you naked. Trigger price source matters as much: exchanges can trigger off last trade, mark price, or index price. Binance futures uses `workingType: MARK_PRICE` or `CONTRACT_PRICE` (last); Bybit v5 uses `triggerBy: MarkPrice/LastPrice/IndexPrice`. Prefer mark-price triggers for protective stops so a single wick or liquidation print on one venue does not stop you out. On Binance spot, stop orders are `STOP_LOSS`/`STOP_LOSS_LIMIT`/`TAKE_PROFIT(_LIMIT)` types with `stopPrice`; there is no mark price on spot.",
    category: "Orders and fills",
    kind: "fact",
  },
  {
    title: "How do I place an OCO order on Binance spot?",
    body: "OCO (one-cancels-the-other) on Binance spot is an order LIST: `POST /api/v3/orderList/oco` (the older `/api/v3/order/oco` endpoint is deprecated as of early 2026 — verify current docs). You pass `price` (limit-maker take-profit leg), `stopPrice` and `stopLimitPrice` (stop-limit leg) plus `stopLimitTimeInForce`. When one leg fills, the exchange cancels the other automatically. Track the list status, not just individual order ids — both legs appear as separate orders. OCO does not exist on Binance futures; emulate it with two reduceOnly conditional orders and cancel the sibling when one fills. Beware the race: if a fill event arrives during a reconnect gap, both legs can execute — reconcile position via REST before assuming the hedge worked.",
    category: "Orders and fills",
    kind: "example",
  },
  {
    title: "How are partial fills and avgPrice reported?",
    body: "A 200 response never means 'filled'. Read `status` (`NEW`, `PARTIALLY_FILLED`, `FILLED`) and `executedQty` every time. On Binance spot the response carries `cummulativeQuoteQty` — your volume-weighted average price is `cummulativeQuoteQty / executedQty`; with `newOrderRespType=FULL` you also get a `fills[]` array with per-fill price, qty, commission and `commissionAsset` (fees may be in BNB, so net received quantity is less than executed). Binance futures returns `avgPrice` directly. Bybit v5 reports `avgPrice`, `cumExecQty`, `cumExecFee` on the order. For PnL and position sizing always accumulate from fills/executed quantities, never from your requested quantity — this is the single most common accounting bug in retail bots.",
    category: "Orders and fills",
    kind: "rule",
  },
  {
    title: "How do I safely retry a timed-out order without double-filling?",
    body: "Always attach a client order id: `newClientOrderId` (Binance), `orderLinkId` (Bybit v5), `clOrdId` (OKX). If a place-order request times out, the outcome is unknown — the exchange may have accepted it. Recovery pattern: query the order BY CLIENT ID (`GET /api/v3/order` with `origClientOrderId`, Bybit `/v5/order/realtime?orderLinkId=`, OKX `GET /api/v5/trade/order?clOrdId=`). If it exists, adopt its real status and stop retrying. If it does not exist, resubmit — on most exchanges a duplicate client id of a still-open order is rejected, which makes the retry idempotent; on resubmit after a confirmed miss you may reuse or rotate the id per exchange semantics. Generate ids deterministically (hash of strategy+signal) so crashes survive restarts.",
    category: "Orders and fills",
    kind: "pitfall",
  },
  {
    title: "What is reduceOnly and when must I set it?",
    body: "`reduceOnly` is a futures-only flag guaranteeing the order can only shrink (or close) your position; the exchange rejects or adjusts it if it would open/increase one. Set it on every stop-loss and take-profit leg. Without it, the classic disaster is: TP fills, your cancel of the SL is lost in a reconnect, the SL later fires and OPENS an opposite position you never intended. On Binance futures set `reduceOnly=true` (or `closePosition=true` on stop-market/take-profit-market to close the whole position without a quantity — note `closePosition` cannot be combined with quantity). In hedge mode also pass the matching `positionSide`. Bybit v5: `reduceOnly: true`. OKX: `reduceOnly: true` on the order. There is no reduceOnly on spot — selling more than you hold is just rejected for insufficient balance.",
    category: "Orders and fills",
    kind: "rule",
  },
  {
    title: "How do I read tickSize, stepSize and minNotional from exchangeInfo?",
    body: "Per symbol, `GET /api/v3/exchangeInfo` (spot) or `/fapi/v1/exchangeInfo` (futures) returns `filters`: `PRICE_FILTER.tickSize` (price must be a multiple), `LOT_SIZE.stepSize` (quantity multiple, min/max), `MIN_NOTIONAL`/`NOTIONAL` (min order value, often ~5-10 USDT), `MARKET_LOT_SIZE` (separate quantity bounds for MARKET orders), and futures adds `PERCENT_PRICE` (price band around mark). Values are strings like `0.00100000` — keep them as decimals/strings, never floats. Cache the response, refresh daily AND on errors like -1013, because exchanges change filters when prices move (a token that 10x'd gets a new tickSize). Bybit equivalent: `GET /v5/market/instruments-info` with `priceFilter`/`lotSizeFilter`; OKX: `/api/v5/public/instruments` with `tickSz`/`lotSz`/`minSz`.",
    category: "Precision and rounding",
    kind: "fact",
  },
  {
    title: "Why does Math.round lose me money on order sizing?",
    body: "Binary floating point: `0.1 + 0.2 = 0.30000000000000004`. Rounding such values to a step size can yield `0.30000001`, which fails `LOT_SIZE` server-side (-1013 'Filter failure'), or silently oversizes a position beyond your balance. Exchanges send all numeric fields as strings for a reason. Use a decimal library (decimal.js, big.js) end to end, or convert to integer ticks: `ticks = floor(qty / step)` then `qty = ticks * step` computed in decimal space. Do all comparisons (notional >= min, qty <= max) in decimals too. Never `parseFloat` an exchange number, do math, and `toFixed` the result — `toFixed` rounds half-to-even-ish on a binary approximation and will betray you at filter boundaries.",
    category: "Precision and rounding",
    kind: "pitfall",
  },
  {
    title: "Which way do I round price and quantity to be safe?",
    body: "Quantity: round DOWN to `stepSize`. Rounding up can exceed your free balance (-2010 insufficient balance) or, worse, make a reduceOnly order larger than the position. Price: round so the order is never MORE aggressive than intended — buys round down to `tickSize`, sells round up. Check `minNotional` AFTER rounding: if `qty * price` lands just below the minimum, bump quantity UP one step (never lower the price to compensate). On truncation vs rounding: Binance historically truncates to filter precision, but behavior can vary by filter and endpoint — do not rely on the exchange to fix your numbers; normalize client-side and prove it with a minimum-size test order. A value that passes your local float check (`0.29999999`) can still fail the server-side decimal check.",
    category: "Precision and rounding",
    kind: "rule",
  },
  {
    title: "How does funding rate work and when is it charged?",
    body: "Perpetual swaps anchor to spot via funding: periodic payments between longs and shorts (positive rate = longs pay shorts). Typical cadence is every 8 hours at 00:00, 08:00, 16:00 UTC on Binance, but many symbols run 4-hour (or even shorter) funding — check per-symbol via funding info endpoints rather than assuming. Fee = `position notional x fundingRate`, and you only pay/receive if you hold the position AT the funding timestamp — bots that enter seconds before funding just to collect it are a known (risky) strategy. History: `GET /fapi/v1/fundingRate`; current predicted rate: `premiumIndex`. Persistent 0.05-0.1% per interval compounds brutally against carry positions — model funding in backtests, or your 'market-neutral' arb is quietly bleeding.",
    category: "Futures specifics",
    kind: "fact",
  },
  {
    title: "Why was my position liquidated when last price never touched my liq price?",
    body: "Because liquidation is decided by MARK price, not last trade. Mark price is a fair-price calculation from the index (multi-venue composite) plus a smoothed basis, designed to resist single-exchange wicks and manipulation. Your chart shows last price on one venue; the engine watches mark. Consequences: a violent wick in last price may NOT liquidate you (good), and a slow index drift can liquidate you while your chart looks fine (surprising). Monitor the `markPriceUpdate` stream (futures) or `premiumIndex` for the real trigger level, and compute your liq price from the documented formula (depends on wallet balance, bracket, maintenance margin) — do not approximate it as `entry x (1 - 1/leverage)`, that is wrong once funding, fees, and tiers enter.",
    category: "Futures specifics",
    kind: "pitfall",
  },
  {
    title: "Cross vs isolated margin — what is the practical difference for a bot?",
    body: "Cross margin backs every position with the whole futures wallet: positions survive deeper drawdowns, but one runaway position can drain the entire account and cascade-liquidate the rest. Isolated caps each position's loss at its assigned margin (adjustable via add/reduce margin endpoints), but liquidates that position sooner. For bots: isolated is the blast-radius limiter when running multiple strategies on one account; cross is capital-efficient for hedged books. Binance sets it per symbol via `POST /fapi/v1/marginType`, and the change is rejected while a position or open order exists on that symbol. Portfolio margin / unified account modes (Binance PM, OKX multi-currency, Bybit UTA) change the math again — read margin state from account endpoints instead of assuming.",
    category: "Futures specifics",
    kind: "fact",
  },
  {
    title: "One-way vs hedge mode (dualSidePosition) — what breaks if I mix them up?",
    body: "One-way mode: one net position per symbol, orders use `positionSide=BOTH`. Hedge mode (`dualSidePosition=true` on Binance): separate LONG and SHORT positions coexist per symbol, and EVERY order must carry `positionSide=LONG` or `SHORT`. Mixing them up throws -4061 ('Order's position side does not match user's setting'), and worse, logic written for one-way silently flips or doubles positions in hedge mode. Query the mode at startup (`GET /fapi/v1/positionSide/dual`) instead of assuming; switching mode is rejected with open positions. Bybit v5 encodes the same thing as `positionIdx`: 0 one-way, 1 hedge-buy side, 2 hedge-sell side. OKX has long/short mode per account with `posSide` on orders. Bake the mode into your order-construction layer, not into scattered if-statements.",
    category: "Futures specifics",
    kind: "pitfall",
  },
  {
    title: "What are leverage brackets, maintenance margin tiers, and ADL?",
    body: "Max leverage falls as position notional grows (e.g. 125x on BTC only for small notionals), and each bracket has its own maintenance margin rate — so your liquidation price JUMPS when growing a position across a tier boundary. Fetch brackets via `GET /fapi/v1/leverageBracket` and size positions inside a tier deliberately. ADL (auto-deleveraging): when the insurance fund cannot cover a bankrupt position, the exchange force-closes profitable opposing positions by ranking (profit x leverage); check the ADL quantile indicator in position data — a high ranking on a big winning position is a real, often ignored, risk. Insurance funds on the major venues absorb negative balances (no socialized clawback on Binance/Bybit as of early 2026), but that is a policy backstop, not a contractual guarantee.",
    category: "Futures specifics",
    kind: "fact",
  },
  {
    title: "How do I keep a Binance user data stream alive (listenKey)?",
    body: "Pattern: `POST /api/v3/userDataStream` (spot) or `POST /fapi/v1/listenKey` (futures) returns a listenKey; connect to the WS endpoint with that key in the path. Keepalive: `PUT` the same endpoint every 30 minutes — the key dies after 60 minutes without one, and the stream silently stops. On reconnect, mint a FRESH key. Events: `executionReport` (order/fill updates) and `outboundAccountPosition` (balances) on spot; `ORDER_TRADE_UPDATE` and `ACCOUNT_UPDATE` on futures. Treat REST account snapshot + stream deltas as your authoritative state. As of early 2026 Binance has been migrating user data toward direct WebSocket-API session subscriptions (`session.logon`) — the listenKey pattern still works, but verify current docs before building new integrations.",
    category: "WebSocket and reconnects",
    kind: "fact",
  },
  {
    title: "How do I maintain a local order book from the diff depth stream?",
    body: "Canonical recipe: 1) open the diff stream (`<symbol>@depth@100ms`) and BUFFER incoming events; 2) fetch a REST snapshot (`GET /api/v3/depth?limit=1000`; futures `/fapi/v1/depth` — mind the higher weight for deep limits); 3) drop buffered events with `u <= snapshot.lastUpdateId`; 4) the first applied event must satisfy `U <= lastUpdateId + 1 <= u`, proving continuity; 5) from then on, each event's `pu` must equal the previous event's `u` — any mismatch is a gap: discard everything and restart from step 1. Apply deltas level by level; a quantity of `0` removes the level. Depth beyond the snapshot limit is invisible, so choose the limit to cover your strategy's price range. Never try to 'skip ahead' after a gap — full resync, always.",
    category: "WebSocket and reconnects",
    kind: "example",
  },
  {
    title: "What do the u, U and pu fields mean and when do I resync?",
    body: "In Binance diff depth events: `U` = first update ID in this event, `u` = last update ID, `pu` = the `u` of the PREVIOUS event (chain-continuity check; `pu` arrived on spot later than on futures — verify per stream). A single event can straddle your snapshot point, which is exactly why the alignment rule is `U <= lastUpdateId+1 <= u`, not a simple equality. Gaps happen on any disconnect, TCP stall, or exchange overload — you usually cannot distinguish 'no updates' from 'lost updates' except via `pu` or a silent timeout on a busy symbol. Resync triggers: `pu` mismatch, socket error, heartbeat timeout, or a stale book (no event for N seconds on an active symbol). Log resync counts; frequent resyncs mean your snapshot/apply loop is too slow, not that the exchange is flaky.",
    category: "WebSocket and reconnects",
    kind: "rule",
  },
  {
    title: "How should I handle ping/pong and reconnects on exchange WebSockets?",
    body: "Binance sends protocol-level ping frames about every 3 minutes and drops the connection if no pong arrives within ~10 minutes — most libraries auto-pong, but custom stacks must reply, and an event loop blocked by heavy book processing will miss pongs. Connections are also capped in lifetime (roughly 24h on Binance spot), so schedule rolling reconnects instead of treating drops as anomalies. Bybit v5 and OKX require APPLICATION-level pings (send `{\"op\":\"ping\"}` / `ping` every ~20 s) on top of protocol frames. On every reconnect: resubscribe all streams, refresh the listenKey/session, resync order books, and reconcile private state via REST. Back off with jitter — a fleet reconnecting in lockstep after an exchange blip is how you earn a REST ban while already wounded.",
    category: "WebSocket and reconnects",
    kind: "rule",
  },
  {
    title: "Why must I reconcile via REST after any WebSocket gap?",
    body: "User data streams are at-most-once: during a reconnect, fills and balance changes are lost, and there is no replay. After any gap (or suspected gap) pull ground truth from REST: open orders (`GET /api/v3/openOrders`, futures `/fapi/v1/openOrders`), positions (`/fapi/v2/positionRisk`), and balances (`GET /api/v3/account`, `/fapi/v2/account`), then rebuild local state from the REST answer — REST wins every conflict. Make fill processing idempotent regardless: the same fill can legitimately arrive via both a WS event and a REST poll, so dedupe by trade id. Also schedule a periodic full reconcile (every few minutes) even without detected gaps — silent state drift is the failure mode you do not see until PnL does not tie out.",
    category: "WebSocket and reconnects",
    kind: "pitfall",
  },
  {
    title: "Unified vs implicit methods in CCXT — which should I use?",
    body: "Unified methods (`createOrder`, `fetchBalance`, `fetchOrder`, `fetchMyTrades`) are normalized across exchanges — use them for anything portable. Implicit methods are auto-generated raw REST wrappers (`privateGetOrder`, `fapiPrivatePostListenKey`) for everything the unified API does not cover: OCO, listenKey keepalives, sub-account transfers, leverage brackets. Mixing both in one bot is normal and expected. Unified responses normalize `price`, `amount`, `filled`, `average`, `status`, `fee` — but exchange-specific data (commission asset, funding, reduceOnly flags, bracket info) lives only in the raw `info` field of the response. Caveat: normalized `status` strings lose nuance (e.g. expired-vs-canceled); when order lifecycle matters, check `info.status` too.",
    category: "CCXT recipes",
    kind: "fact",
  },
  {
    title: "How do I pass exchange-specific parameters through CCXT createOrder?",
    body: "`createOrder(symbol, type, side, amount, price, params)` merges `params` into the raw request — this is the escape hatch for every exchange-specific flag. Binance futures: `{ timeInForce: 'GTX', reduceOnly: true, positionSide: 'LONG', workingType: 'MARK_PRICE', stopPrice: 95000 }`. Bybit v5: `{ triggerPrice: 95000, triggerBy: 'MarkPrice', tpslMode: 'Full', orderLinkId: 'my-id-123' }`. OKX: `{ tdMode: 'isolated', clOrdId: 'x', reduceOnly: true }`. Params are passed through essentially unchecked: a typo silently becomes an ignored field, and the order succeeds WITHOUT the protection you meant to attach (the classic is a misspelled reduceOnly on a stop leg). Verify flags landed by fetching the order back and inspecting `info`, and prove behavior with minimum-size test orders.",
    category: "CCXT recipes",
    kind: "example",
  },
  {
    title: "How should I handle CCXT errors (NetworkError vs ExchangeError)?",
    body: "CCXT's taxonomy maps to retry strategy. `NetworkError` subclasses (`RequestTimeout`, `ExchangeNotAvailable`, `DDoSProtection`) are transient: retry with backoff — BUT for write operations (create/cancel order) a timeout means unknown outcome, so reconcile by client order id before resubmitting, not blindly. `ExchangeError` subclasses (`BadSymbol`, `InvalidOrder`, `InsufficientFunds`, `AuthenticationError`, `BadRequest`) are deterministic: retrying changes nothing, fix the request. `RateLimitExceeded` sits between: wait per `Retry-After`, then retry. CCXT picks the subclass from exchange error codes, so catch narrowly (`except InsufficientFunds`) instead of swallowing broad exceptions. Always log `err.message` — it embeds the raw exchange code (-1021, 10006, 50011) you need for debugging.",
    category: "CCXT recipes",
    kind: "rule",
  },
  {
    title: "Which CCXT options gotchas bite the most?",
    body: "Top offenders: 1) `binance.options['defaultType']` defaults to `'spot'` — set `'swap'` for USD-M perps or `fetchBalance`/`fetchPositions` silently query the wrong account. 2) `enableRateLimit: true` turns on the built-in token bucket — without it, any loop will eventually eat a 429/418; set it on every instance, and remember each CCXT instance has its OWN limiter. 3) `setSandboxMode(true)` switches to testnet/demo URLs — testnet books are thin and behavior differs from prod; validate plumbing there, not strategy. 4) `loadMarkets()` caches markets in memory; long-running bots must reload periodically (delistings, changed precision) or trade on stale filters. 5) `options.adjustForTimeDifference` auto-fixes -1021 by syncing server time. 6) Per-exchange `options` like `defaultType` also affect `fetchOHLCV`/`fetchOrderBook` market resolution.",
    category: "CCXT recipes",
    kind: "pitfall",
  },
  {
    title: "ccxt.pro watch() vs REST polling — what are the tradeoffs?",
    body: "`ccxt.pro` watch methods (`watchOrderBook`, `watchTrades`, `watchOrders`, `watchBalance`) maintain a WebSocket-backed cache: far lower latency and no REST weight cost, but you inherit every WS failure mode — gaps, stale caches, silent disconnects. For order books, check the exchange-specific nonce/sequence handling and be ready to resync; for private state, still reconcile against REST periodically. Polling (`fetch*`) is slower and burns rate-limit budget but is self-healing: every call is ground truth. Practical split: watch for market data (latency-sensitive, self-correcting), watch + scheduled REST reconcile for orders/positions, pure poll for low-frequency accounting. Note `fetchOrder(id)` is not universal: some exchanges cannot fetch old/filled orders by id — fall back to `fetchClosedOrders`/`fetchOrders` and filter client-side.",
    category: "CCXT recipes",
    kind: "fact",
  },
  {
    title: "My bot got IP-banned after an outage — how do I avoid retry storms?",
    body: "Classic failure: exchange API blips, every strategy instance retries instantly in a tight loop, the IP hits 429 then 418, and now you are banned for hours-to-days DURING the volatility you wanted to trade. Prevention: one shared throttled HTTP client per process (all strategies draw from the same budget); exponential backoff with full jitter on every 429/5xx; a circuit breaker on 418 that halts trading and pages you; and bounded concurrency for order placement. After recovery, expect a flood of stale state — reconcile via REST before resuming order flow, and assume every in-flight order's outcome is unknown until queried. Log ban events with headers (`Retry-After`, used-weight) so you can tune budgets from evidence, not guesses.",
    category: "Production pitfalls",
    kind: "pitfall",
  },
  {
    title: "Why is my balance slightly less than my accounting says (dust and BNB fees)?",
    body: "Spot fees are taken per fill, often in the received asset or in BNB: net received quantity is less than `executedQty`, so position sizing off gross quantities drifts over hundreds of trades. The BNB fee discount (as of early 2026, roughly 25% on spot — verify the current rate) silently consumes your BNB balance; when BNB runs out, fees flip back to the traded asset and your cost model changes mid-flight — alert on low BNB. Leftover dust (balances below `minNotional`) cannot be sold on the book; sweep periodically via small-asset conversion (convert dust to BNB) or book it as a cost. Futures fees are simpler (quote currency per fill) but funding payments hit the wallet balance and therefore move your liquidation price — another quiet drift to account for.",
    category: "Production pitfalls",
    kind: "pitfall",
  },
  {
    title: "What production traps hide in markets cache, testnet, keys, and withdrawals?",
    body: "Markets: refresh `loadMarkets`/`exchangeInfo` on a schedule and on -1013/BadSymbol errors — delisted pairs and changed tick sizes break stale caches at the worst time. Testnet ≠ prod: thin books, generous fills, sometimes different limits and features; validate plumbing on testnet, then re-validate sizing with minimum live orders. Keys: env vars or a secret manager, never in the repo or logs; trade-only permissions (disable withdrawals), IP whitelist on, separate keys per bot so one compromise does not drain everything. Withdrawals: API withdrawal needs explicit permission, and new addresses may require a whitelist with a holding delay — never design a strategy that depends on instant withdrawals. Finally: clock drift and filter changes are the two 'worked yesterday' causes — monitor both before blaming the exchange.",
    category: "Production pitfalls",
    kind: "pitfall",
  },
  {
    title: "How do stop orders work on Binance SPOT, and which trigger price applies?",
    body: "Spot stop orders use dedicated order types: STOP_LOSS (triggers a MARKET sell when the last trade price falls to stopPrice), STOP_LOSS_LIMIT (triggers a LIMIT sell at your price), and TAKE_PROFIT / TAKE_PROFIT_LIMIT mirrored upward. Key facts that differ from futures: spot has NO mark price — the trigger is always the last traded price, there is no workingType parameter; STOP_LOSS (market) gives no guaranteed execution price — in a fast dump the fill can be far below stopPrice, while the _LIMIT variant can fail to fill at all and leave you holding through the drop. For combined take-profit + stop-loss on one position use an OCO order (orderList/oco): a limit-maker leg plus a stop-limit leg, where filling one cancels the other. Place stops via the same order endpoints with stopPrice in the request; verify the order is resting as a working conditional order, not executed immediately (stopPrice on the wrong side of the market triggers instantly).",
    category: "Orders and fills",
    kind: "fact",
  },
  {
    title: "How do I read remaining rate-limit quota on Bybit v5 and OKX?",
    body: "Bybit v5 returns quota in response headers: X-Bapi-Limit (the per-endpoint cap), X-Bapi-Limit-Status (remaining in the current window), X-Bapi-Limit-Reset-Timestamp (window reset, unix ms). Limits are per-endpoint per-UID and vary by account tier, so read the headers live instead of hardcoding numbers — log them when you approach the cap. OKX documents limits per endpoint as 'N requests per 2 seconds' (order endpoints are typically 60/2s for placement as of early 2026, but verify per endpoint and tier in the docs) and returns error code 50011 when breached; OKX does not give a uniform X-RateLimit-* header family across REST endpoints, so track client-side: a token bucket per endpoint group keyed to the documented window. On both exchanges, back off on the first breach — repeated hammering after 50011/10006 escalates from throttling to temporary bans.",
    category: "Rate limits and bans",
    kind: "rule",
  },
  {
    title: "My market order didn't fill immediately — is that normal?",
    body: "Usually yes, and the causes are diagnosable. Partial fill: book depth at the top levels is smaller than your size — the remainder of a spot MARKET order either fills walking the book or expires (Binance spot market orders fill what liquidity allows; check executedQty vs origQty, and the fills array for per-trade prices). Rejected outright: notional below the pair's minNotional/MIN_NOTIONAL filter — a $3 order on a $5-minimum pair never reaches the book, and this is the most common 'nothing happened' cause; also price/quantity precision filters. Delayed: during volatility spikes the matching engine and API gateway queue — REST ack can lag seconds while the order is actually live, which is why you must never blind-retry: query the order by clientOrderId first. Slippage: a large market order walks multiple levels — read avgPrice from fills, not the ticker price you saw when sending.",
    category: "Orders and fills",
    kind: "pitfall",
  },
  {
    title: "Do WebSocket connections have rate limits, or are they unlimited?",
    body: "They have limits, on two layers. Connection layer: Binance caps new WS connections per IP (5 per minute historically — verify current), and streams drop after 24 hours by design, so reconnect logic is mandatory; invalid frames or too many subscription messages per connection get the socket closed. Order layer: the Binance WebSocket API (placing orders over WS) carries its own order rate limit — 10 orders per second per connection, plus the same per-account order limits as REST; exceeding returns an error frame, and abuse closes the connection. Bybit v5 WS enforces per-endpoint and per-connection message limits with its own retCodes; OKX applies account-level limits to WS order channels too. Design rule: one WS connection multiplexed for streams, REST for burst order flow, and never assume a socket that accepted your message executed it — confirm via the execution report or a REST order query.",
    category: "Rate limits and bans",
    kind: "fact",
  },
];
