/**
 * Render the README demo: an animated SVG of a terminal session.
 *
 *   npx tsx scripts/demo-svg.ts > public/brand/demo.svg
 *
 * An SVG rather than a GIF on purpose — it is ~10 KB instead of megabytes,
 * stays sharp on any display, renders on GitHub without a player, and is
 * regenerated by editing the script below rather than re-recording a screen.
 */

interface Line {
  text: string;
  /** ink | prompt | tool | ok | dim */
  tone?: "ink" | "prompt" | "tool" | "ok" | "dim";
  /** Seconds before this line appears. */
  at: number;
}

const LINES: Line[] = [
  { at: 0.0, text: "$ claude mcp add --transport http mozg https://mozg.sh/mcp", tone: "prompt" },
  { at: 0.9, text: "✓ connected · 5 brains available", tone: "ok" },
  { at: 1.6, text: "" },
  { at: 1.8, text: "> does EAS Update need a new build when I change a channel?", tone: "ink" },
  { at: 2.9, text: "" },
  { at: 3.1, text: "  brain_search(brain: \"mozg/expo\", query: \"eas update channel branch\")", tone: "tool" },
  { at: 3.9, text: "  → 4 notes · 96 ms · zero context tokens", tone: "dim" },
  { at: 4.6, text: "" },
  { at: 4.8, text: "  No. A channel points at a branch, and the build reads whichever" },
  { at: 5.2, text: "  update matches its channel header and runtime version — relink" },
  { at: 5.6, text: "  the channel and existing builds follow it." },
  { at: 6.3, text: "" },
  { at: 6.5, text: "  source: mozg/expo — exam score 72%, updated today", tone: "dim" },
];

const W = 860;
const PAD = 22;
const LH = 22;
const TOP = 58;
const H = TOP + LINES.length * LH + PAD;
const LOOP = 9.5;

const COLOR = {
  ink: "#e9eaec",
  prompt: "#f15060",
  tool: "#7aa2f7",
  ok: "#3ec300",
  dim: "#8b8f98",
} as const;

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// Every line animates on ONE clock of LOOP seconds, with its entrance
// encoded in keyTimes. Per-line `begin` with per-line `dur` would drift
// apart after the first cycle — the second loop would play as noise.
const rows = LINES.map((l, i) => {
  const y = TOP + i * LH;
  const fill = COLOR[l.tone ?? "ink"];
  const t = l.at / LOOP;
  const inDone = Math.min(t + 0.02, 0.9);
  return `  <text x="${PAD}" y="${y}" fill="${fill}" opacity="0">${esc(l.text)}
    <animate attributeName="opacity" values="0;0;1;1;0"
      keyTimes="0;${t.toFixed(4)};${inDone.toFixed(4)};0.94;1"
      dur="${LOOP}s" repeatCount="indefinite" />
  </text>`;
}).join("\n");

process.stdout.write(`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace" font-size="13.5">
  <rect width="${W}" height="${H}" rx="10" fill="#14161a" />
  <rect width="${W}" height="34" rx="10" fill="#1d2027" />
  <rect y="24" width="${W}" height="10" fill="#1d2027" />
  <circle cx="20" cy="17" r="5" fill="#f15060" />
  <circle cx="38" cy="17" r="5" fill="#f5c04e" />
  <circle cx="56" cy="17" r="5" fill="#3ec300" />
  <text x="76" y="22" fill="#8b8f98" font-size="12">claude code — mozg</text>
${rows}
</svg>
`);
