/**
 * Vendor the web fonts into the repo.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * next/font/google downloads from fonts.gstatic.com at BUILD time, which makes
 * every build depend on a network call to a third party. That failed twice in
 * one afternoon here — "Error while requesting resource", build aborted, with
 * nothing wrong in the code — and a build that fails for reasons outside the
 * repository is a build you cannot trust or reproduce. Worse, it would fail the
 * same way in CI or on a self-hoster's machine behind a firewall.
 *
 * So the files live in public/fonts and the @font-face rules live in
 * src/app/fonts.css. Re-run this only to update a family or add a weight; the
 * output is committed.
 *
 * Google serves one file per subset with a unicode-range, which is why this
 * writes the rules by hand rather than using next/font/local — that helper has
 * no way to express unicode-range, so a single "latin + cyrillic" face would
 * mean shipping Cyrillic glyphs to every English reader.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const FAMILIES = [
  { name: "Unbounded", css: "Unbounded:wght@700;800", weights: [700, 800] },
  { name: "Golos Text", css: "Golos+Text:wght@400;500;600", weights: [400, 500, 600] },
  { name: "JetBrains Mono", css: "JetBrains+Mono:wght@400;500;700", weights: [400, 500, 700] },
];

/** What the product actually renders. latin-ext carries the accented Latin. */
const SUBSETS = ["latin", "latin-ext", "cyrillic"];

// Without a modern UA, Google serves legacy formats instead of woff2.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const OUT_DIR = join(process.cwd(), "public", "fonts");
const CSS_PATH = join(process.cwd(), "src", "app", "fonts.css");

/** Google labels each block with a `/* subset *\/` comment above it. */
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const [, subset, body] = m;
    const url = body.match(/src:\s*url\(([^)]+)\)/)?.[1];
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (url && weight && range) faces.push({ subset, url, weight: Number(weight), range: range.trim() });
  }
  return faces;
}

const rules = [];

await mkdir(OUT_DIR, { recursive: true });

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.css}&display=swap`;
  const css = await fetch(url, { headers: { "user-agent": UA } }).then((r) => r.text());

  const wanted = parseFaces(css).filter(
    (f) => SUBSETS.includes(f.subset) && family.weights.includes(f.weight),
  );
  if (!wanted.length) throw new Error(`no faces matched for ${family.name}`);

  for (const face of wanted) {
    const slug = family.name.toLowerCase().replace(/\s+/g, "-");
    const file = `${slug}-${face.weight}-${face.subset}.woff2`;
    const bytes = Buffer.from(await fetch(face.url).then((r) => r.arrayBuffer()));
    await writeFile(join(OUT_DIR, file), bytes);

    rules.push(
      `/* ${family.name} ${face.weight} · ${face.subset} */\n` +
        `@font-face {\n` +
        `  font-family: "${family.name}";\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${face.weight};\n` +
        `  font-display: swap;\n` +
        `  src: url("/fonts/${file}") format("woff2");\n` +
        `  unicode-range: ${face.range};\n` +
        `}`,
    );
    console.log(`${file}  ${(bytes.length / 1024).toFixed(0)} KB`);
  }
}

await writeFile(
  CSS_PATH,
  "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.\n" +
    "   Vendored so a build never depends on fonts.gstatic.com answering. */\n\n" +
    rules.join("\n\n") +
    "\n",
);
console.log(`\nwrote ${CSS_PATH} — ${rules.length} faces`);
